myT$Pathogens[myT$Pathogens == "MRSA"] = "S. aureus"                                                     
myT$Pathogens[myT$Pathogens == "Klebsiella spp."] = "Klebsiella spp"                                                     
myT$Pathogens[myT$Pathogens == "Enterobacter spp."] = "Enterobacter spp"      
myT$Pathogens[myT$Pathogens == "Pseudomonas spp."] = "Pseudomonas spp"                                                     
myT$Pathogens[myT$Pathogens == "Enterococci"] = "Enterococcus spp"  
myT$Pathogens[myT$Pathogens == "Streptococci"] = "Streptococcus spp"                                                     
myT$Pathogens[myT$Pathogens == "E. Coli"] = "E. coli"                                                     
myT$Pathogens[myT$Pathogens == "S. Aureus "] = "S. aureus"                                                     
myT$Pathogens[myT$Pathogens == "Klebsiella"] = "Klebsiella spp"                                                     
myT$Pathogens[myT$Pathogens == "Citrobacter"] = "Citrobacter spp"                                                     
myT$Pathogens[myT$Pathogens == "Enterococcus"] = "Enterococcus spp"                                                     
myT$Pathogens[myT$Pathogens == "Enterobacter species"] = "Enterobacter spp"                                                     
myT$Pathogens[myT$Pathogens == "A. Baumanii"] = "A. baumanii"                                                     
myT$Pathogens[myT$Pathogens == "P. Aeruginosa"] = "P. aeruginosa"                                                     
myT$Pathogens[myT$Pathogens == "Clostridium spp."] = "Clostridium spp"                                                     
myT$Pathogens[myT$Pathogens == "E. coli "] = "E. coli"                                                     
myT$Pathogens[myT$Pathogens == "Enterobacter spp. "] = "Enterobacter spp"                                                     
myT$Pathogens[myT$Pathogens == "Acinobacter spp."] = "Acinobacter spp"                                                     
myT$Pathogens[myT$Pathogens == "Proteus"] = "Proteus spp"      
myT$Pathogens[myT$Pathogens == "Proteus spp."] = "Proteus spp"                                                     
myT$Pathogens[myT$Pathogens == "Enterococcus spp."] = "Enterococcus spp"                                                     
myT$Pathogens[myT$Pathogens == "Acinetobacter spp."] = "Acinobacter spp"                                                     
myT$Pathogens[myT$Pathogens == "S. aureus "] = "S. aureus"                                                     
myT$Pathogens[myT$Pathogens == "Acinetobacter baumanii"] = "A. baumannii"                                                     
myT$Pathogens[myT$Pathogens == "Pseudomonas aeruginosa"] = "P. aeruginosa"                                                     
myT$Pathogens[myT$Pathogens == "Salmonella enterica"] = "Salmonella spp NT"                                                     
myT$Pathogens[myT$Pathogens == "Shigella spp."] = "Shigella spp" 
myT$Pathogens[myT$Pathogens == "Salmonella"] = "Salmonella spp NT"                                                     
myT$Pathogens[myT$Pathogens == "A. baumanii"] = "A. baumannii"                                                     
myT$Pathogens[myT$Pathogens == "Acinetobacter sp."] = "Acinetobacter spp"                                                     
myT$Pathogens[myT$Pathogens == "A. baumanni"] = "A. baumannii"                                                     
myT$Pathogens[myT$Pathogens == "P. aeurginosa"] = "P. aeruginosa"                                                  
myT$Pathogens[myT$Pathogens == "S. aureaus"] = "S. aureus"                                                  
myT$Pathogens[myT$Pathogens == "P. auroginosa"] = "P. aeruginosa"                                                   
myT$Pathogens[myT$Pathogens == "P. mirabilis "] = "P. mirabilis"                                                   
myT$Pathogens[myT$Pathogens == "Klebsiella spp. "] = "Klebsiella spp"                                                   
myT$Pathogens[myT$Pathogens == "Citrobacter spp. "] = "Citrobacter spp"                                                   
myT$Pathogens[myT$Pathogens == "Providencia spp. "] = "Providencia spp"                                                   
myT$Pathogens[myT$Pathogens == "A. buamannii"] = "A. baumannii"                                                   
myT$Pathogens[myT$Pathogens == "Serratia spp. "] = "Serratia spp"                                                   
myT$Pathogens[myT$Pathogens == "Providencia spp"] = "Providencia spp"                                                  
myT$Pathogens[myT$Pathogens == "E. faacalis"] = "E. faecalis"                                                  
myT$Pathogens[myT$Pathogens == "K. pneumoniae "] = "K. pneumoniae"                                                  
myT$Pathogens[myT$Pathogens == "P. aeruginosa."] = "P. aeruginosa"                                                  
myT$Pathogens[myT$Pathogens == "Staphylococcus"] = "Staphylococcus spp"                                                  
myT$Pathogens[myT$Pathogens == "Pseudomonas"] = "Pseudomonas spp"                                                  
myT$Pathogens[myT$Pathogens == "Salmonella spp."] = "Salmonella spp"                                                  
myT$Pathogens[myT$Pathogens == "Acinetobacter baumannii"] = "A. baumannii"                                              
myT$Pathogens[myT$Pathogens == "Staphylococcus sp"] = "Staphylococcus spp"                                              
myT$Pathogens[myT$Pathogens == "Enterobacter sp"] = "Enterobacter spp"                                              
myT$Pathogens[myT$Pathogens == "Serratia sp"] = "Serratia spp"                                              
myT$Pathogens[myT$Pathogens == "Providencia sp"] = "Providencia spp"                                              
myT$Pathogens[myT$Pathogens == "Proteus mirabilis sp"] = "P. mirabilis"                                                   
myT$Pathogens[myT$Pathogens == "Citrobacter sp"] = "Citrobacter spp"                                            
myT$Pathogens[myT$Pathogens == "Shigella sp"] = "Shigella spp"                                          
myT$Pathogens[myT$Pathogens == "Staphylococcus spp."] = "Staphylococcus spp"                                         
myT$Pathogens[myT$Pathogens == "P. aeruginosa "] = "P. aeruginosa"                                          
myT$Pathogens[myT$Pathogens == "Klebsiella oxytoca"] = "K. oxytoca"                                           
myT$Pathogens[myT$Pathogens == "Klebsiella ozanae"] = "K. ozanae"                                           
myT$Pathogens[myT$Pathogens == "S.epidermidis" ] = "S. epidermidis"                                          
myT$Pathogens[myT$Pathogens == "Enteroccus spp."] = "Enteroccus spp"                                        
myT$Pathogens[myT$Pathogens == "Klebsiella pneumoniae"] = "K. pneumoniae"                                       
myT$Pathogens[myT$Pathogens == "Pseudonomas aeruginosa"] = "P. aeruginosa"                                       
myT$Pathogens[myT$Pathogens == "Acinobacter baumannii"] = "A. baumannii"                                        
myT$Pathogens[myT$Pathogens == "Staphylococcus aureus"] = "S. aureus"                                        
myT$Pathogens[myT$Pathogens == "Enterococcus faecalis"] = "E. faecalis"                                           
myT$Pathogens[myT$Pathogens == "S.haemolyticus"] = "S. haemolyticus"  
myT$Pathogens[myT$Pathogens == "Enterococcus faecium"  ] = "E. faecium"  
myT$Pathogens[myT$Pathogens == "H influenzae"] = "H. influenzae"   
myT$Pathogens[myT$Pathogens == "S.aureus"] = "S. aureus"   
myT$Pathogens[myT$Pathogens == "coagulase-negative Staphylococcus spp." ] = "Staphylococcus spp" 
myT$Pathogens[myT$Pathogens == "beta-Streptococcus haemolyticus"] = "S. haemolyticus" 
myT$Pathogens[myT$Pathogens == "K. oxycota"] = "K. oxytoca"
myT$Pathogens[myT$Pathogens == "Staphylococcus epidermidis"] = "S. epidermidis"
myT$Pathogens[myT$Pathogens == "Streptococcus pneumoniae"] = "S. pneumoniae"                                 
myT$Pathogens[myT$Pathogens == "Enterococcus faecalis "] = "E. faecalis"                                 
myT$Pathogens[myT$Pathogens == "Enterococcus faecium "] = "E. faecium" 
myT$Pathogens[myT$Pathogens == "Vancomycin-Resistant Enterococcus faecalis "] = "E. faecalis"                                
myT$Pathogens[myT$Pathogens == "Vancomycin-Resistant Enterococcus faecium "] = "E. faecium"                                 
myT$Pathogens[myT$Pathogens == "Citrobacter spp."] = "Citrobacter spp"                                
myT$Pathogens[myT$Pathogens == "Neisseria"] = "Neisseria spp"                                                                                
myT$Pathogens[myT$Pathogens == "Acientobacter spp."] = "Acenitobacter spp"                                                                                
myT$Pathogens[myT$Pathogens == "Klebisella spp."] = "Klebisella spp"                                                                                 
myT$Pathogens[myT$Pathogens == "Acenitobacter spp."] = "Acenitobacter spp"                                                                                
myT$Pathogens[myT$Pathogens == "K.pneumoniae, K.oxytoca, K. ornithinolytica"] = "Klebisella spp"                                                                                
myT$Pathogens[myT$Pathogens == "K.pneumoniae"  ] = "K. pneumoniae"   
myT$Pathogens[myT$Pathogens == "E.coli"] = "E. coli"                                                                                  
myT$Pathogens[myT$Pathogens == "E.Coli"] = "E. coli"                                                                                  
myT$Pathogens[myT$Pathogens == "E. Coli "] = "E. coli"                                                                                  
myT$Pathogens[myT$Pathogens == "K.oxytoca"] = "K. oxytoca"                                                                                 
myT$Pathogens[myT$Pathogens == "A.buamannii"] = "A. baumannii"                                                                                   
myT$Pathogens[myT$Pathogens == "Acinetobacter spp. "] = "Acinetobacter spp"                                                                                   
myT$Pathogens[myT$Pathogens == "A.baumannii"] = "A. baumannii"                                                                                   
myT$Pathogens[myT$Pathogens == "K.pneumoniaem, K.terrigena, K.oxytoca, K.ornithinolytica"] = "Klebisella spp"                                                                                   
myT$Pathogens[myT$Pathogens == "A.baumannii, A.pittii, A.nosocomialis"] = "Acinetobacter spp"                                                                               
myT$Pathogens[myT$Pathogens == "S. Aureus"] = "S. aureus"                                                                               
myT$Pathogens[myT$Pathogens == "E Coli"] = "E. coli"                                                                               
myT$Pathogens[myT$Pathogens == "E coli"] = "E. coli"                                                                               
myT$Pathogens[myT$Pathogens == "Acinetobacterbacter"] = "Acinetobacterbacter spp"                                                                               
myT$Pathogens[myT$Pathogens == "K. Spp"] = "Klebisella spp"                                                                               
myT$Pathogens[myT$Pathogens == "S. pneumoniae "] = "S. pneumoniae"                                                                               
myT$Pathogens[myT$Pathogens == "E.faecalis"] = "E. faecalis"                                                                               
myT$Pathogens[myT$Pathogens == "E.faecium"] = "E. faecium"                                                                               
myT$Pathogens[myT$Pathogens == "P.areuginosa"] = "P. aeruginosa"                                                                               
myT$Pathogens[myT$Pathogens == "K pneumoniae"] = "K. pneumoniae"                                                                               
myT$Pathogens[myT$Pathogens == "S aureus"] = "S. aureus"                                                                               
myT$Pathogens[myT$Pathogens == "A baumanii"] = "A. baumannii"                                                                                
myT$Pathogens[myT$Pathogens == "P aeruginosa"] = "P. aeruginosa"                                                                                
myT$Pathogens[myT$Pathogens == "K. Pneumoniae"] = "K. pneumoniae"                                                                                 
myT$Pathogens[myT$Pathogens == "Escherichia coli"] = "E. coli"                                                                                  
myT$Pathogens[myT$Pathogens == "staphylococcus aureus"] = "S. aureus"                                                                                  
myT$Pathogens[myT$Pathogens == "MSSA"] = "S. aureus"                                                                                  
myT$Pathogens[myT$Pathogens == "Streptococcus agalactiae"] = "S. agalactiae"  
myT$Pathogens[myT$Pathogens == "Streptococcus pyogenes"] = "S. pyogenes"                                                                                  
myT$Pathogens[myT$Pathogens == "Streptococcus viridans"] = "S. viridans"                                                                                  
myT$Pathogens[myT$Pathogens == "Klebisella spp"] = "Klebsiella spp"                                                                                 
myT$Pathogens[myT$Pathogens == "K. ozaenae"] = "K. ozanae"
myT$Pathogens[myT$Pathogens == "K.pneumoniaem, K.terrigena, K.oxytoca, K.ornithinolytica"] = "Klebsiella spp"                                                                                 
myT$Pathogens[myT$Pathogens == "Acinetobacter"] = "Acinetobacter spp"
myT$Pathogens[myT$Pathogens == "Acinobacter spp"] = "Acinetobacter spp"  
myT$Pathogens[myT$Pathogens == "K.oxytoca, K.pneumoniae, K.ornithinolytica, K.sp"] = "Klebisella spp"                                                                               
myT$Pathogens[myT$Pathogens == "A.baumannii, A.haemolyticus, A.lwoffii, A.sp"] = "Acinetobacterbacter spp" 

print(unique(myT$Pathogens))

# Table of number of rates per pathogen
myT$count = rep(1,nrow(myT))
myST = aggregate(myT$count, by = list(myT$Pathogens), FUN = sum)
names(myST) = c("Pathogens","count")
myST = myST[rev(order(myST$count)),]
print(myST)

# Pooling
###########################################################################
myT$PathogensG = rep(NA,nrow(myT))
myT$PathogensG[myT$Pathogens %in% c("E. coli","Shigella spp")] = "E. coli"
myT$PathogensG[myT$Pathogens %in% c("K. pneumoniae","Klebsiella spp","K. oxytoca","K. aerogenes","K. ozaenae","K. ozanae","K. aerogenes")] = "Klebsiella spp"
myT$PathogensG[myT$Pathogens %in% c("S. aureus","Klebsiella spp","Staphylococcus spp")] = "Staphylococcus spp"
myT$PathogensG[myT$Pathogens %in% c("A. baumannii","Acinobacter spp")] = "Acinetobacter spp"
myT$PathogensG[myT$Pathogens %in% c("P. aeruginosa","Pseudomonas spp")] = "Pseudomonas spp"
myT$PathogensG[myT$Pathogens %in% c("Enterobacter spp","E. faecalis","E. faecium","E. cloacae","E. aerogens")] = "Enterobacter spp"
myT$PathogensG[myT$Pathogens %in% c("Acinetobacter spp")] = "Acinetobacter spp"
myT$PathogensG[myT$Pathogens %in% c("Salmonella spp","Salmonella spp NT")] = "Salmonella spp"







